-- MySQL Script generated by MySQL Workbench
-- 12/08/15 15:39:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Manager` (
  `MG_id` INT NOT NULL,
  `MG_name` VARCHAR(45) NOT NULL,
  `MG_phone` VARCHAR(45) NULL,
  `MG_salary` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`MG_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `e_id` INT NOT NULL,
  `e_name` VARCHAR(45) NOT NULL,
  `e_address` VARCHAR(45) NOT NULL,
  `e_phone` VARCHAR(45) NULL,
  PRIMARY KEY (`e_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Manages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Manages` (
  `MG_id` INT NOT NULL,
  `e_id` INT NOT NULL,
  PRIMARY KEY (`MG_id`, `e_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Warehouse` (
  `w_num` INT NOT NULL,
  `w_name` VARCHAR(45) NOT NULL,
  `w_location` VARCHAR(45) NOT NULL,
  `w_size` VARCHAR(45) NULL,
  PRIMARY KEY (`w_num`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Item` (
  `i_id` INT NOT NULL,
  `i_name` VARCHAR(45) NOT NULL,
  `i_price` VARCHAR(45) NOT NULL,
  `qty_left` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`i_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stored_in`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Stored_in` (
  `w_num` INT NOT NULL,
  `i_id` INT NOT NULL,
  PRIMARY KEY (`w_num`, `i_id`),
  INDEX `fk_Warehouse_has_Item_Item1_idx` (`i_id` ASC),
  INDEX `fk_Warehouse_has_Item_Warehouse1_idx` (`w_num` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = swe7;


-- -----------------------------------------------------
-- Table `mydb`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Supplier` (
  `s_id` INT NOT NULL,
  `s_name` VARCHAR(45) NOT NULL,
  `s_location` VARCHAR(45) NOT NULL,
  `s_size` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`s_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Provides`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Provides` (
  `Item_i_id` INT NOT NULL,
  `Supplier_s_id` INT NOT NULL,
  `p_date` DATE NOT NULL,
  `p_quantity` VARCHAR(45) NOT NULL,
  `shipment_size` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Item_i_id`, `Supplier_s_id`),
  INDEX `fk_Item_has_Supplier_Supplier1_idx` (`Supplier_s_id` ASC),
  INDEX `fk_Item_has_Supplier_Item1_idx` (`Item_i_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `c_id` INT NOT NULL,
  `c_name` VARCHAR(45) NOT NULL,
  `c_address` VARCHAR(45) NULL,
  `c_email` VARCHAR(45) NULL,
  PRIMARY KEY (`c_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Assistant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Assistant` (
  `e_id` INT NOT NULL,
  `a_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`e_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `o_num` INT NOT NULL,
  `o_date` DATE NOT NULL,
  `peyment_method` VARCHAR(45) NOT NULL,
  `c_id` INT NOT NULL,
  `e_id` INT NOT NULL,
  PRIMARY KEY (`o_num`),
  INDEX `fk_Order_Customer1_idx` (`c_id` ASC),
  INDEX `fk_Order_Assistant1_idx` (`e_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Maintenance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Maintenance` (
  `e_id` INT NOT NULL,
  `num_repairs` VARCHAR(45) NULL,
  PRIMARY KEY (`e_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`IT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`IT` (
  `i_id` INT NOT NULL,
  `i_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`i_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TV`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TV` (
  `i_id` INT NOT NULL,
  `tv_size` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`i_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kitchen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kitchen` (
  `i_id` INT NOT NULL,
  `k_category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`i_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Communication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Communication` (
  `i_id` INT NOT NULL,
  `com_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`i_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Accessories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Accessories` (
  `i_id` INT NOT NULL,
  `a_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`i_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Audio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Audio` (
  `i_id` INT NOT NULL,
  `au_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`i_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contains`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contains` (
  `o_num` INT NOT NULL,
  `i_id` INT NOT NULL,
  PRIMARY KEY (`o_num`, `i_id`),
  INDEX `fk_Order_has_Item_Item1_idx` (`i_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Brand` (
  `b_name` VARCHAR(45) NOT NULL,
  `popularity` VARCHAR(45) NOT NULL,
  `market_share` VARCHAR(45) NOT NULL,
  `country_of_origin` VARCHAR(45) NOT NULL,
  `i_id` INT NOT NULL,
  PRIMARY KEY (`b_name`, `i_id`),
  INDEX `fk_Brand_Item1_idx` (`i_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
