-- MySQL Script generated by MySQL Workbench
-- 12/10/15 00:42:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `e_id` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NULL,
  `e_address` VARCHAR(45) NOT NULL,
  `e_phone` VARCHAR(45) NULL,
  `Employee_e_id` INT NOT NULL,
  PRIMARY KEY (`e_id`, `Employee_e_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Warehouse` (
  `w_num` INT NOT NULL,
  `w_name` VARCHAR(45) NOT NULL,
  `w_location` VARCHAR(45) NOT NULL,
  `w_size` VARCHAR(45) NULL,
  PRIMARY KEY (`w_num`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `c_id` INT NOT NULL,
  `c_name` VARCHAR(45) NOT NULL,
  `c_address` VARCHAR(45) NULL,
  `c_email` VARCHAR(45) NULL,
  PRIMARY KEY (`c_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Assistant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Assistant` (
  `a_type` VARCHAR(45) NOT NULL,
  `Employee_e_id` INT NOT NULL,
  PRIMARY KEY (`Employee_e_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `o_num` INT NOT NULL,
  `o_date` DATE NOT NULL,
  `peyment_method` VARCHAR(45) NOT NULL,
  `e_id` INT NOT NULL,
  `Customer_c_id` INT NOT NULL,
  `Assistant_Employee_e_id` INT NOT NULL,
  PRIMARY KEY (`o_num`, `Customer_c_id`, `Assistant_Employee_e_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Brand` (
  `b_name` VARCHAR(45) NOT NULL,
  `popularity` VARCHAR(45) NOT NULL,
  `market_share` VARCHAR(45) NOT NULL,
  `country_of_origin` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`b_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Maintanance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Maintanance` (
  `num_repairs` VARCHAR(45) NULL,
  `Employee_e_id` INT NOT NULL,
  PRIMARY KEY (`Employee_e_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Item` (
  `i_id` INT NOT NULL,
  `i_name` VARCHAR(45) NOT NULL,
  `i_price` VARCHAR(45) NOT NULL,
  `qty_left` VARCHAR(45) NOT NULL,
  `Warehouse_w_num` INT NOT NULL,
  `Order_o_num` INT NOT NULL,
  `Order_Customer_c_id` INT NOT NULL,
  `Brand_b_name` VARCHAR(45) NOT NULL,
  `Maintanance_Employee_e_id` INT NOT NULL,
  PRIMARY KEY (`i_id`, `Warehouse_w_num`, `Order_o_num`, `Order_Customer_c_id`, `Brand_b_name`, `Maintanance_Employee_e_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Supplier` (
  `s_id` INT NOT NULL,
  `s_name` VARCHAR(45) NOT NULL,
  `s_location` VARCHAR(45) NOT NULL,
  `s_size` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`s_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Provides`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Provides` (
  `Item_i_id` INT NOT NULL,
  `Supplier_s_id` INT NOT NULL,
  `p_date` DATE NOT NULL,
  `p_quantity` VARCHAR(45) NOT NULL,
  `shipment_size` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Item_i_id`, `Supplier_s_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`IT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`IT` (
  `i_id` INT NOT NULL,
  `i_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`i_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TV`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TV` (
  `i_id` INT NOT NULL,
  `tv_size` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`i_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kitchen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kitchen` (
  `i_id` INT NOT NULL,
  `k_category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`i_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Communication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Communication` (
  `i_id` INT NOT NULL,
  `com_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`i_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Accessories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Accessories` (
  `i_id` INT NOT NULL,
  `a_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`i_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Audio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Audio` (
  `i_id` INT NOT NULL,
  `au_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`i_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Payroll`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Payroll` (
  `P_number` INT NOT NULL,
  `gross_pay` VARCHAR(45) NULL,
  `bonus` VARCHAR(45) NULL,
  `deductions` VARCHAR(45) NULL,
  `from_date` VARCHAR(45) NULL,
  `to_date` VARCHAR(45) NULL,
  `net_pay` VARCHAR(45) NULL,
  `Employee_e_id` INT NOT NULL,
  PRIMARY KEY (`P_number`, `Employee_e_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cashier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cashier` (
  `checkout_No` INT NOT NULL,
  `revenue_per_day` VARCHAR(45) NULL,
  `Employee_e_id` INT NOT NULL,
  PRIMARY KEY (`Employee_e_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bill` (
  `B_num` INT NOT NULL,
  `amount` VARCHAR(45) NULL,
  `Order_o_num` INT NOT NULL,
  `Order_Customer_c_id` INT NOT NULL,
  `Cashier_Employee_e_id` INT NOT NULL,
  PRIMARY KEY (`B_num`, `Order_o_num`, `Order_Customer_c_id`, `Cashier_Employee_e_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
